import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';

const scriptPath = path.resolve('tampermonkey.js');
const source = fs.readFileSync(scriptPath, 'utf8');

assert.match(source, /action_delay_min_ms:\s*\d+/, 'tampermonkey.js must expose action_delay_min_ms');
assert.match(source, /action_delay_max_ms:\s*\d+/, 'tampermonkey.js must expose action_delay_max_ms');
assert.match(source, /send_delay_min_ms:\s*\d+/, 'tampermonkey.js must expose send_delay_min_ms');
assert.match(source, /send_delay_max_ms:\s*\d+/, 'tampermonkey.js must expose send_delay_max_ms');
assert.match(source, /send_accept_timeout_ms:\s*\d+/, 'tampermonkey.js must expose send_accept_timeout_ms');
assert.match(source, /send_accept_poll_ms:\s*\d+/, 'tampermonkey.js must expose send_accept_poll_ms');
assert.match(source, /assistant_post_stop_timeout_ms:\s*\d+/, 'tampermonkey.js must expose assistant_post_stop_timeout_ms');
assert.match(source, /function randomBetween\(min,\s*max\)/, 'tampermonkey.js must define randomBetween()');
assert.match(source, /await sleep\(randomBetween\(config\.action_delay_min_ms,\s*config\.action_delay_max_ms\)\)/, 'SET_PROMPT path must wait with action delay');
assert.match(source, /await sleep\(randomBetween\(config\.send_delay_min_ms,\s*config\.send_delay_max_ms\)\)/, 'CLICK_SEND path must wait with send delay');
assert.match(source, /function buildTurnContext\(snapshot,\s*commandId\)/, 'tampermonkey.js must define buildTurnContext()');
assert.match(source, /function isSendAccepted\(reasons\)/, 'tampermonkey.js must define isSendAccepted()');
assert.match(source, /function chatRootElement\(\)/, 'message parsing must be scoped to the chat root');
assert.match(source, /root\.querySelectorAll\('\[data-message-author-role\]'\)/, 'messageElements must not query the whole document');
assert.match(source, /function imageSummary\(root\)/, 'message parsing must include image metadata');
assert.match(source, /image_count:\s*images\.length/, 'each parsed message must expose image_count');
assert.match(source, /acc\.images = \(acc\.images \|\| 0\) \+ item\.image_count;/, 'message counts must include total images');
assert.match(source, /lastAcceptedTurnContext = turnContext;/, 'CLICK_SEND must persist accepted turn context');
assert.match(source, /reason:\s*'missing_send_accept_context'/, 'WAIT_ASSISTANT_DONE must fail without accepted turn context');
assert.match(source, /if \(snapshot\.stop_visible\) \{[\s\S]*?continue;/, 'WAIT_ASSISTANT_DONE must keep waiting while stop_visible is true');
assert.match(source, /function handleNavigateNewChat\(command\)/, 'tampermonkey.js must implement new-chat navigation');
assert.match(source, /action === 'NEW_CHAT' \|\| action === 'NAVIGATE_NEW'/, 'NEW_CHAT and NAVIGATE_NEW must be supported');
assert.match(source, /window\.location\.assign\('\/'\)/, 'new-chat navigation must use the current tab to open ChatGPT root');
assert.match(source, /function handleReloadPage\(command,\s*hard = false\)/, 'tampermonkey.js must implement explicit page reload commands');
assert.match(source, /action === 'RESET_PAGE' \|\| action === 'RELOAD_PAGE' \|\| action === 'RELOAD'/, 'reset and reload commands must be supported');
assert.match(source, /action === 'HARD_RELOAD'/, 'hard reload command must be supported');
assert.match(source, /function handleCloseWindow\(command\)/, 'tampermonkey.js must implement close-window command with browser-block reporting');
assert.match(source, /WINDOW_CLOSE_BLOCKED/, 'close-window command must report when the browser blocks tab closing');
assert.match(source, /function handleUploadFiles\(command\)/, 'tampermonkey.js must implement browser file upload command');
assert.match(source, /function uploadPayloadFiles\(payload\)/, 'file upload must rebuild File objects from payload');
assert.match(source, /base64ToBytes\(data\)/, 'file upload must decode local file bytes in browser');
assert.match(source, /new File\(\[bytes\], name, \{ type \}\)/, 'file upload must create real File objects');
assert.match(source, /new ClipboardEvent\('paste'/, 'file upload must support clipboard-style paste');
assert.match(source, /new DragEvent\(eventName/, 'file upload must support drag/drop fallback');
assert.match(source, /querySelectorAll\('input\[type="file"\]'\)/, 'file upload must support file-input fallback');
assert.match(source, /action === 'UPLOAD_FILE' \|\| action === 'UPLOAD_FILES' \|\| action === 'PASTE_IMAGE' \|\| action === 'PASTE_FILES'/, 'upload command aliases must be routed');
assert.match(source, /composer_attachments:/, 'domSnapshot must expose composer attachment metadata');

assert.match(source, /function dismissUploadOverlays\(\)/, 'upload flow must detect and dismiss stale upload overlays');
assert.match(source, /already uploaded this file/, 'upload overlay cleanup must handle duplicate-file modal');
assert.match(source, /dismiss_overlay_before_upload/, 'UPLOAD_FILES must run overlay cleanup before injecting files');
assert.match(source, /method === 'auto' \? \['input', 'paste', 'drop'\]/, 'UPLOAD_FILES auto mode must prefer input before paste/drop to avoid duplicate overlay');
assert.match(source, /const checkAfterAttempt = async \(label\)/, 'UPLOAD_FILES must check success after each individual target attempt');
assert.match(source, /if \(succeededMethod\) \{\s*break;\s*\}/, 'UPLOAD_FILES must stop trying more targets after first successful upload');
assert.doesNotMatch(source, /function roleFromUrl\(\)/, 'bridge must not read role from URL');
assert.doesNotMatch(source, /setRole\(urlRole\)/, 'bridge must not persist URL-provided role');
assert.doesNotMatch(source, /searchParams\.set\('mauto_role'/, 'bridge must not write role into URL');
assert.match(source, /api\/claim-role/, 'bridge must claim queued roles through the local server');
assert.match(source, /function clearRole\(\)/, 'bridge must define an explicit role clear path');
assert.match(source, /sessionStorage\.removeItem\('chatgpt_agent_role'\)/, 'clearing role must remove per-tab session role');
assert.match(source, /localStorage\.removeItem\('chatgpt_agent_role'\)/, 'clearing role must remove legacy persisted localStorage role');
assert.doesNotMatch(source, /localStorage\.setItem\('chatgpt_agent_role'/, 'role must not be shared across tabs through localStorage');
